<div class="alert alert-block alert-warning">
    import <b>Libraries</b>
</div>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

<div class="alert alert-block alert-warning">
    <b>LOAD DATASET</b>
</div>

In [2]:
train_data = pd.read_csv('train.csv')
train_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [3]:
test_data = pd.read_csv('test.csv')
test_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

<div class="alert alert-block alert-warning">
    <b>FEATURE SELECTION</b>
</div>

In [4]:
numerical_cols = ['Age', 'RoomService', 'FoodCourt',
                  'ShoppingMall', 'Spa', 'VRDeck']

categorical_cols = ['HomePlanet', 'Destination',
                    'VIP', 'CryoSleep']

X = train_data[numerical_cols + categorical_cols]
y = train_data['Transported'].astype(int)

X_test = test_data[numerical_cols + categorical_cols]

<div class="alert alert-block alert-warning">
    <b>PREPROCESSING</b>
</div>

In [5]:
num_transformer = SimpleImputer(strategy='median')

cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(transformers=[
    ('num', num_transformer, numerical_cols),
    ('cat', cat_transformer, categorical_cols)
])

<div class="alert alert-block alert-warning">
    <b>MODEL</b>
</div>

In [6]:
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        random_state=42
    ))
])

<div class="alert alert-block alert-warning">
    <b>TRAIN & VALIDATION</b>
</div>

In [7]:
X_train, X_valid, y_train, y_valid = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model.fit(X_train, y_train)

predictions = model.predict(X_valid)

print("Accuracy:",
      accuracy_score(y_valid, predictions))

Accuracy: 0.7924094307073031

<div class="alert alert-block alert-warning">
    <b>FINAL PREDICTION</b>
</div>

In [8]:
test_predictions = model.predict(X_test)

submission = pd.DataFrame({
    'PassengerId': test_data.PassengerId,
    'Transported': test_predictions.astype(bool)
})

submission.to_csv('submission.csv', index=False)

print("File created successfully.")

File created successfully.